# 01.yaml - Cloudformation Tutorial - Ticketea training material
#
# Prerequisites:
# - A valid AWS account :-)
# - An ssh key pair
# - Switch to Frankfurt region
# - Write down your ip address
#
# Template topics:
# - JSON vs Yaml
# - Analyze line-by-line
#
AWSTemplateFormatVersion: 2010-09-09
Description: A single ec2 instance

Parameters:
    SSHKey:
        Description: The SSH Key that will be used to connect to our instance
        Type: AWS::EC2::KeyPair::KeyName  # see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
    AllowConnectionFrom:
        Description: Allow ssh connection from this specific CIDR range (eg. 1.2.3.4/32)
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})' # eg. 1.1.1.1/32
        ConstraintDescription: Must be a valid CIDR

Resources:
    PublicSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: SG rules to apply within the public subnets
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: !Ref AllowConnectionFrom

    MyInstance1:
        Type: AWS::EC2::Instance
        Properties:
            KeyName: !Ref SSHKey
            InstanceType: t2.micro
            ImageId: ami-97e953f8  # ubuntu 16.04 in eu-central-1
            SecurityGroupIds: [!Ref PublicSecurityGroup]

Outputs:
    MyInstancePublicIp:
        Description: Public IP of our EC2 machine
        Value: !GetAtt MyInstance1.PublicIp
