#
# 04.yaml - Cloudformation Tutorial - Ticketea training material
#
# Template topics:
#
# - Mappings
# - Fn::Select GetAZ (multi-region)
#
AWSTemplateFormatVersion: 2010-09-09

Description: Elastic Load balanacer with two webservers - multi-region ready

Parameters:
    SSHKey:
        Description: The SSH Key that will be used to connect to our instance
        Type: AWS::EC2::KeyPair::KeyName  # see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
    AllowConnectionFrom:
        Description: Allow ssh connection from this specific CIDR range (eg. 1.2.3.4/32)
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})' # eg. 1.1.1.1/32
        ConstraintDescription: Must be a valid CIDR
    AZ1:
        Type: AWS::EC2::AvailabilityZone::Name
        Description: The first availability zone
    AZ2:
        Type: AWS::EC2::AvailabilityZone::Name
        Description: The second availability zone

Mappings:

  RegionMap:
    eu-west-1:  # Ireland
      WebserverAMI: ami-add175d4  # ubuntu 16.04
    eu-central-1:  # Frankfurt
      WebserverAMI: ami-97e953f8  # ubuntu 16.04


Resources:
    PublicSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: SG rules to apply within the public subnets
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: !Ref AllowConnectionFrom
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0

    MyInstance1:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: !Select
                - 0
                - Fn::GetAZs: !Ref 'AWS::Region'  # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html
            KeyName: !Ref SSHKey
            InstanceType: t2.micro
            SecurityGroupIds: [!Ref PublicSecurityGroup]
            ImageId:
              !FindInMap
              - RegionMap
              - !Ref AWS::Region
              - WebserverAMI
            UserData:
                Fn::Base64: !Sub |
                  #!/bin/bash -e
                  apt-get update
                  apt-get -y install nginx-light
                  echo "<h1>Hi, my name is $HOSTNAME@${AWS::Region}</h1>" > /var/www/html/index.html
            Tags:
            - Key: Name
              Value:
                Fn::Join: # fn.join('-', [stackname, staticfileserver])
                - "-"
                - - !Ref AWS::StackName
                  - StaticFilesServer

    MyInstance2:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: !Select
                - 1
                - Fn::GetAZs: !Ref 'AWS::Region'  # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html
            KeyName: !Ref SSHKey
            InstanceType: t2.micro
            SecurityGroupIds: [!Ref PublicSecurityGroup]
            ImageId:
              !FindInMap  # like FindInMap("RegionMap", ref("aws:region"), "WebserverAMI")
              - RegionMap
              - !Ref AWS::Region
              - WebserverAMI
            UserData:
                Fn::Base64: !Sub |
                  #!/bin/bash -e
                  apt-get update
                  apt-get -y install nginx-light
                  echo "<h1>Hi, my name is $HOSTNAME@${AWS::Region}</h1>" > /var/www/html/index.html
            Tags:
            - Key: Name
              Value:
                Fn::Join: # fn.join('-', [stackname, staticfileserver])
                - "-"
                - - !Ref AWS::StackName
                  - StaticFilesServer

    MyLoadBalancer:
        Type: AWS::ElasticLoadBalancing::LoadBalancer
        Properties:
            AvailabilityZones: [!Ref AZ1, !Ref AZ2]
            CrossZone: true
            Instances:
                - !Ref MyInstance1
                - !Ref MyInstance2
            Listeners:
                - LoadBalancerPort: 80
                  InstancePort: 80
                  Protocol: HTTP
            HealthCheck:
                Target: HTTP:80/
                HealthyThreshold: 2
                UnhealthyThreshold: 5
                Interval: 5
                Timeout: 3

Outputs:
    WebserverPublicIp:
        Description: Public IP of our Load Balancer.
        Value: !GetAtt MyLoadBalancer.DNSName

